name: 打包应用的actions
on:
    push: # 监听代码时间
        branches:
            - master # master分支代码推送的时候激活当前action
jobs:
    build:
        # runs-on 操作系统
        runs-on: ubuntu-latest
        steps:
            - name: 迁出代码
              uses: actions/checkout@master
            # 安装Node
            - name: 安装Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14.7.6
            # 安装依赖
            - name: 安装依赖
              run: npm install
            # 打包
            - name: 打包
              run: npm run build
